### PR TITLE
Add IPv6 support to portcheck service

### LINKED ISSUE #1: Portcheck broken for ipv6 capable systems.
Migrated from https://github.com/transmission/transmission/issues/3102

>Portcheck has been broken for ipv6 capable systems since the DNS AAAA record was added back in 2017 https://github.com/transmission/transmission/issues/381. When the system resolves the AAAA record and uses ipv6 for the portcheck request, it receives "400 Bad Request" because the server side script at that URL is not ipv6 capable.

### PR DESCRIPTION
**Pull request by titer**
Fixes: #1 
* Use getaddrinfo+AI_NUMERICHOST instead of the IPv4-only inet_addr
* Add small test for IPv4 and v6 port checks

### CODE REVIEW

**Comment by kelson42** [comment]
@ckerr Any chance you could review the PR @titer was kind enough to provide? If merged, I guess he could deploy it straight and that way this ~10 years old problem would be finally behind us!

**Review by ckerr — APPROVED** [review]
lgtm. Thanks @titer :green_heart:

**Comment by ckerr** [comment]
@titer next question, how does deployment work? :smile_cat:

**Comment by titer** [comment]
@ckerr thanks for the review!
I'm adding a bit of documentation in #5 - you don't seem to have access yet but I can add your ssh key any time.
This change is now deployed and the IPv6 check works fine for me

**Comment by ckerr** [comment]
@titer TBH the fewer tertiary things I have to know about / care about / fix when they break, the better.  :slightly_smiling_face: 

If it could just redeploy whenever something's merged to the repo that would be so much better than if a year from now I have to dig out my notes on how I deployed it back in March of '23

**Comment by kelson42** [comment]
@ckerr We could build automatically a container image here using Github actions and then we just need to find a way to trigger the recreation of the container?! Something like https://hub.docker.com/r/containrrr/watchtower/ might be a solution. This is at least the kind of approach I would choose.

**Comment by ckerr** [comment]
I just want it to work; however @titer wants to do is fine with me.

...though it is nice to see Eric again thanks to this portcheck feature, so maybe it's sometimes a Good Thing for something to break once in awhile :smile_cat:

**Comment by dunxd** [comment]
Just spotted this.  Since my router doesn't support UPNP for IPv6 I am getting an error message that the port is not open. However, it is open for IPv4 and downloads are working fine. Perhaps an orange indicator and "Port open for IPv4 only" message in this scenario would be more helpful.

If I manually open the port for IPv6 this works, but that requires firewall reconfig everytime I open Transmission.

I opened this as a separate issue when I started seeing the port showing as closed in the settings page: https://github.com/transmission/portcheck/issues/7

**Comment by ckerr** [comment]
Marking comment as off-topic since portcheck.transmissionbt.com is just a website service; it has no concept of Transmission's UI e.g. an indicator "port open for ipv4 only"

**Pull request merged**
